<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Online Blood Donation System</title>
<link href="css/bootstrap.css" rel="stylesheet" type="text/css">
<link href="css/common.css" rel="stylesheet" type="text/css">
</head>
<body>
<header class="header_area_holder container-fluid text-center">
  <div class="row">
      <div class="col-md-12">
          <h1>Online Blood Donation System</h1>
        </div>
    </div>
</header>
<footer class="footer_area_holder container-fluid text-center">
  <div class="row">
      <div class="col-md-12">
          <p><a href="https://www.floxblog.com/" target="_blank">Flox Blog</a> 2019.</p>
        </div>
    </div>
</footer>
</body>
</html>